/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursierapi_internal_jniutils_ApiInternalNativeApi */

#ifndef _Included_coursierapi_internal_jniutils_ApiInternalNativeApi
#define _Included_coursierapi_internal_jniutils_ApiInternalNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    terminalSizeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_terminalSizeNative
  (JNIEnv *, jclass);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    enableAnsiOutputNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_enableAnsiOutputNative
  (JNIEnv *, jclass);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    GetUserEnvironmentVariableNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_GetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    SetUserEnvironmentVariableNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_SetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    DeleteUserEnvironmentVariableNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_DeleteUserEnvironmentVariableNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    GetKnownFolderPathNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_GetKnownFolderPathNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coursierapi_internal_jniutils_ApiInternalNativeApi
 * Method:    GetModuleFileNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_ApiInternalNativeApi_GetModuleFileNameNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
